# Generated by Django 3.2.7 on 2021-11-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211124_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('payment_status', 'can view all post')]},
        ),
    ]
