# Generated by Django 3.2.7 on 2021-11-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
