# Generated by Django 3.2.9 on 2021-11-24 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='contentent',
        ),
    ]
